name: EconomyLand
main: onebone\economyland\EconomyLand
api: 5.0.0
version: "4.0.0"
author: onebone
depend: [EconomyAPI]

permissions:
 economyland:
  description: Allows player to use all functions in EconomyLand
  default: op
 economyland.land:
  description: Allows player to access all lands
  default: op
economyland.land.modify.others:
  description: Allows player to modify others' lands
  default: op
economyland.land.modify.whiteland:
  description: Allows player to modify white lands
  default: op
economyland.land.give.others:
  description: Allows player to give others' land to others'
  default: op
economyland.land.move:
  description: Allows player move to land
  default: op
economyland.land.move.others:
  description: Allows player move to others' land
  default: true
economyland.landsell:
  description: Gives permission player to access all land selling function
  default: op
economyland.landsell.others:
  description: Allows player to sell others' land
  default: op

economyland.command:
 description: Allows player to use all commands in EconomyLand
 default: op
economyland.command.land:
 description: Allows player to use land command
 default: true
economyland.command.land.pos:
 description: Allows player to set positions for setting land
 default: true
economyland.command.land.buy:
 description: Allows player to buy land
 default: true
economyland.command.land.option:
 description: Allows player to edit option of land
 default: true
economyland.command.land.sell:
 description: Allows player to sell land
 default: true
economyland.command.land.move:
 description: Allows player to move to other land
 default: true
economyland.command.land.list:
 description: Allows player to see list of lands
 default: true
economyland.command.land.whose:
 description: Allows player to see list of lands with specified keyword
 default: true
economyland.command.land.give:
 description: Allows player give land to other
 default: true
economyland.command.land.here:
 description: Allows player to see what land player is standing on
 default: true
economyland.command.land.invite:
 description: Allows player to invite players
 default: true
economyland.command.land.invite.remove:
 dà from the list
 default: true
economyland.command.land.invite.remove.others:
 default: op

